name: agraguard
description: Agricultural pest management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  provider: ^6.1.2
  translator: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.7
  http: ^1.2.0
  camera: ^0.11.3
  camera_android: ^0.10.10+11
  flutter_markdown: ^0.6.16
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon_3.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon_2.png"
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/pests/
    - assets/logo.jpg
    - lib/NDVI.jpeg
    - assets/profile.png



